language: go

go:
  - 1.3
  - tip
  
sudo: true

install:
  - sudo apt-get install libcap2-bin
  - go get
  - make
  - /bin/ls
  - ./jailingo run --root /tmp/jail /bin/ls
script: go test -v -race ./...
